


// move
export function gameCurrentStateToString(): string {
  return `GAME_STATE:GAME_STATE:CURRENT_ROUND:CURRENT_ROUND:ROUND_STATE:ROUND_STATE:CURRENT_ENTRY:CURRENT_ENTRY:ENTRY_STATE:ENTRY_STATE`;
}