export const DRAW_DUO_STATE_PENDING = 'DRAW_DUO_STATE_PENDING';
export const DRAW_DUO_STATE_INITIATING = 'DRAW_DUO_STATE_INITIATING';
export const DRAW_DUO_STATE_PLAYING = 'DRAW_DUO_STATE_PLAYING';
export const DRAW_DUO_STATE_COMPLETED = 'DRAW_DUO_STATE_COMPLETED';

export const DRAW_DUO_ROUND_STATE_PENDING = 'DRAW_DUO_ROUND_STATE_PENDING';
export const DRAW_DUO_ROUND_STATE_DRAWING = 'DRAW_DUO_ROUND_STATE_DRAWING';
export const DRAW_DUO_ROUND_STATE_VOTING = 'DRAW_DUO_ROUND_STATE_VOTING';
export const DRAW_DUO_ROUND_STATE_RESULTS = 'DRAW_DUO_ROUND_STATE_RESULTS';
export const DRAW_DUO_ROUND_STATE_COMPLETED = 'DRAW_DUO_ROUND_STATE_COMPLETED';

export const DRAW_DUO_ENTRY_STATE_PENDING = 'DRAW_DUO_ENTRY_STATE_PENDING';
export const DRAW_DUO_ENTRY_STATE_GUESSING = 'DRAW_DUO_ENTRY_STATE_GUESSING';
export const DRAW_DUO_ENTRY_STATE_VOTING = 'DRAW_DUO_ENTRY_STATE_VOTING';
export const DRAW_DUO_ENTRY_STATE_RESULTS = 'DRAW_DUO_ENTRY_STATE_RESULTS';
export const DRAW_DUO_ENTRY_STATE_COMPLETED = 'DRAW_DUO_ENTRY_STATE_COMPLETED';